version = 0.1

[default.deploy.parameters]
stack_name = "pangu-space"
region = "us-east-1"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "CertificateArn=arn:aws:acm:us-east-1:123456789012:certificate/REPLACE-ME"
